name: Reusable Workflow Example

on:
    workflow_call:
        inputs:
          example-input:
            required: false
            type: string

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print input
              run: |
                   array="echo ${{ inputs.example-input }} | xargs"
                   echo "Input: $array"
                   echo "fim"
