name: Reusable Workflow Example

on:
    workflow_call:
        inputs:
          example-input:
            required: false
            type: string

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print input
              run: |
                   input_array=(${{inputs.example-input}})
                   echo "Array elements:"
                   for element in "${input_array[@]}"; do
                     echo "$element"
                   done
                   

