name: Reusable Workflow Example

on:
    workflow_call:
        inputs:
          example-input:
            required: false
            type: string

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print input
              run: |
                   input_array=(${{inputs.example-input}})
                   
                   ls -l 

                   pwd

                   echo "##############################"

                   for element in "${input_array[@]}"; do
                     source "${GITHUB_WORKSPACE}/rm-framework/$element"
                   done
                   

